http://localhost:8080/
Content-Type: application/json

{
  "message": 1
}

###
http://localhost:8080/
Content-Type: application/json

{
  "message": "hello!"
}

###
http://localhost:8080
Content-Type: application/json

{
  "some_other_field": "Sap!"
}